// Minimal ABI subset of LootCartographer needed by the web app's smoke test.
// Generated by hand to keep packages/shared dependency-free; swap for wagmi
// codegen once the broader UI lands.
export const cartographerAbi = [
  {
    type: "function",
    name: "locate",
    stateMutability: "view",
    inputs: [{ name: "bagId", type: "uint256" }],
    outputs: [
      { name: "x", type: "int256" },
      { name: "y", type: "int256" },
    ],
  },
  {
    type: "function",
    name: "regionOf",
    stateMutability: "view",
    inputs: [{ name: "bagId", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "id", type: "uint8" },
          { name: "name", type: "string" },
          { name: "capitalX", type: "int256" },
          { name: "capitalY", type: "int256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "terrainOf",
    stateMutability: "view",
    inputs: [{ name: "bagId", type: "uint256" }],
    outputs: [
      { name: "terrain", type: "uint8" },
      { name: "name", type: "string" },
    ],
  },
] as const;
